# Generated by Django 5.2.8 on 2025-11-17 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LieuStockage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_lieu', models.CharField(max_length=255, unique=True)),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Lieu de Stockage',
                'verbose_name_plural': 'Lieux de Stockage',
            },
        ),
        migrations.CreateModel(
            name='Transporteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Transporteur',
                'verbose_name_plural': 'Transporteurs',
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la Catégorie')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='annonces.categorie', verbose_name='Catégorie Parente')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('etat', models.CharField(choices=[('NEUF', 'Neuf'), ('COMME_NEUF', 'Utilisé mais comme neuf'), ('UTILISE', 'Utilisé')], default='UTILISE', max_length=20)),
                ('pays_depart', models.CharField(max_length=100, verbose_name='Pays de Départ (A)')),
                ('ville_depart', models.CharField(max_length=100, verbose_name='Ville de Départ (A)')),
                ('pays_arrivee', models.CharField(max_length=100, verbose_name="Pays d'Arrivée (B)")),
                ('ville_arrivee', models.CharField(max_length=100, verbose_name="Ville d'Arrivée (B)")),
                ('date_livraison_estimee', models.DateField(blank=True, null=True, verbose_name='Date de livraison estimée')),
                ('methode_livraison', models.CharField(choices=[('1', "Dépositaire s'occupe du transport"), ('2', "Utilisation d'un Transporteur (Choix dans la liste)"), ('3', "Utilisation d'un Lieu de Stockage + Transporteur")], default='1', max_length=1, verbose_name='Méthode Logistique')),
                ('paiement_requis', models.BooleanField(default=False, verbose_name='Paiement requis pour la logistique')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('depositaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces_deposees', to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='annonces.categorie')),
                ('lieu_stockage_choisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='annonces.lieustockage')),
                ('transporteur_choisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='annonces.transporteur')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
            },
        ),
        migrations.CreateModel(
            name='PhotoAnnonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='annonces/images/', verbose_name='Fichier Média')),
                ('is_main', models.BooleanField(default=False, verbose_name='Photo Principale (Obligatoire)')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='annonces.annonce')),
            ],
            options={
                'verbose_name': "Photo de l'Annonce",
                'verbose_name_plural': 'Photos des Annonces',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('annonce',), name='unique_main_photo_par_annonce')],
            },
        ),
    ]
