# Generated by Django 5.2.8 on 2025-11-17 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stockages', '0001_initial'),
        ('transporteurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('etat', models.CharField(choices=[('NEUF', 'Neuf'), ('OCCASION', 'Occasion'), ('ABIME', 'Abimé / Endommagé')], default='OCCASION', max_length=10)),
                ('pays_depart', models.CharField(max_length=100)),
                ('ville_depart', models.CharField(max_length=100)),
                ('pays_arrivee', models.CharField(max_length=100)),
                ('ville_arrivee', models.CharField(max_length=100)),
                ('date_livraison_estimee', models.DateField(blank=True, null=True)),
                ('methode_livraison', models.CharField(choices=[('1', "1. Dépositaire s'occupe du transport"), ('2', '2. Transporteur sélectionné'), ('3', '3. Stockage + Transporteur sélectionné')], default='1', max_length=1)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('paiement_requis', models.BooleanField(default=True, verbose_name="Paiement requis à l'avance")),
                ('depositaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_annonces', to=settings.AUTH_USER_MODEL)),
                ('lieu_stockage_choisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces_stockees', to='stockages.lieustockageprofile')),
                ('transporteur_choisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces_assignees', to='transporteurs.transporteurprofile')),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces', to='annonces.categorie')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ('-date_creation',),
            },
        ),
        migrations.CreateModel(
            name='PhotoAnnonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='annonces_photos/', verbose_name='Fichier Image')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name="Description de l'image (Optionnel)")),
                ('is_main', models.BooleanField(default=False, verbose_name='Photo principale')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='annonces.annonce')),
            ],
            options={
                'verbose_name': "Photo d'Annonce",
                'verbose_name_plural': "Photos d'Annonce",
                'ordering': ('-is_main', 'date_upload'),
            },
        ),
    ]
