# Generated by Django 5.2.8 on 2025-11-17 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='parent_annonce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_annonces', to='annonces.annonce', verbose_name='Annonce Parent (optionnel)'),
        ),
    ]
