# Generated by Django 5.2.8 on 2025-11-17 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0002_annonce_parent_annonce'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['parent__nom', 'nom'], 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AddField(
            model_name='categorie',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='annonces.categorie', verbose_name='Catégorie Parent'),
        ),
    ]
