# Generated by Django 5.2.8 on 2025-11-17 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransporteurProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=150, unique=True, verbose_name="Nom de l'Entreprise/Service")),
                ('description', models.TextField(help_text='Décrivez votre offre, votre expérience et vos garanties.', verbose_name='Description des services')),
                ('licence_transport', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de Licence/Permis')),
                ('pays_base', models.CharField(max_length=50, verbose_name='Pays de base')),
                ('ville_base', models.CharField(max_length=50, verbose_name='Ville principale')),
                ('methodes_transportees', models.CharField(choices=[('Route', 'Transport Routier (Voiture/Camion)'), ('Air', 'Fret Aérien'), ('Mer', 'Fret Maritime'), ('Autres', 'Autres (Course, Relais, etc.)')], default='Route', max_length=10, verbose_name='Méthode principale')),
                ('assurance_incluse', models.BooleanField(default=False, verbose_name='Assurance incluse par défaut')),
                ('transport_dangereux', models.BooleanField(default=False, verbose_name='Transport de matières dangereuses autorisé')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transporteur_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur lié')),
            ],
            options={
                'verbose_name': 'Profil Transporteur',
                'verbose_name_plural': 'Profils Transporteurs',
            },
        ),
    ]
