# Generated by Django 5.2.8 on 2025-11-17 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LieuStockageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_lieu', models.CharField(max_length=150, unique=True, verbose_name='Nom du Lieu de Stockage')),
                ('description', models.TextField(help_text="Décrivez l'espace, la sécurité, et les conditions de stockage.", verbose_name='Description des services de stockage')),
                ('superficie_m2', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Superficie (m²)')),
                ('temperature_controle', models.BooleanField(default=False, verbose_name='Température contrôlée')),
                ('securite_24_7', models.BooleanField(default=False, verbose_name='Sécurité 24/7 (Alarme/Vidéo)')),
                ('pays', models.CharField(max_length=50, verbose_name='Pays')),
                ('ville', models.CharField(max_length=50, verbose_name='Ville')),
                ('adresse_complete', models.CharField(max_length=255, verbose_name='Adresse (Visible seulement après accord)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stockage_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur lié')),
            ],
            options={
                'verbose_name': 'Profil Lieu de Stockage',
                'verbose_name_plural': 'Profils Lieux de Stockage',
            },
        ),
    ]
